# Generated by Django 2.2.5 on 2019-09-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='wish',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
